zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "49181:2181"
    - "22"
nimbus:
  image: wurstmeister/storm-nimbus
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
    - "22"
  links: 
    - zookeeper:zk
supervisor:
  image: wurstmeister/storm-supervisor
  ports:
    - "8000"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
  volumes:
    - /var/log/storm
ui:
  image: wurstmeister/storm-ui
  ports:
    - "49080:8080"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
logstash:
  image: pblittle/docker-logstash
  ports: 
    - "49200:9200"
    - "49292:9292"
  volumes_from:
    - supervisor
  volumes:
    - logstash:/opt/logstash/conf.d

